# Generated by Django 5.2.4 on 2025-07-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_video_file_remove_video_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='videos/default.mp4', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
